<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CatAreasGobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Desactivar la verificación de claves foráneas e ignorar el auto-incremento para insertar IDs específicos
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Opcional: Truncar la tabla antes de insertar para evitar duplicados si se corre varias veces
        DB::table('cat_areas_gob')->truncate();
        
        // Datos a insertar con el campo 'categoria' y 'siglas' actualizado
        $areas = [
            [
                'id_area' => 1,
                'id_area_padre' => NULL,
                'nombre' => 'Despacho del Gobernador',
                'siglas' => 'DESP-GOB',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 2,
                'id_area_padre' => NULL,
                'nombre' => 'Secretariado Ejecutivo del Sistema Estatal de Seguridad Pública',
                'siglas' => 'SESESP',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 3,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Gobierno',
                'siglas' => 'SEGOB',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 4,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Finanzas y Administración',
                'siglas' => 'SFA',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 5,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Contraloría',
                'siglas' => 'SECOEM', // Siglas encontradas en el dump original
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 6,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Seguridad Pública',
                'siglas' => 'SSP',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 7,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Desarrollo Económico',
                'siglas' => 'SEDECO',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 8,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Turismo',
                'siglas' => 'SECTUR',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 9,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Agricultura y Desarrollo Rural',
                'siglas' => 'SADER',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 10,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Comunicaciones y Obras Públicas',
                'siglas' => 'SCOP',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 11,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría del Medio Ambiente',
                'siglas' => 'SMA',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 12,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Desarrollo Urbano y Movilidad',
                'siglas' => 'SEDUM',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 13,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Educación',
                'siglas' => 'SEE',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 14,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Cultura',
                'siglas' => 'SECUM',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 15,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Salud',
                'siglas' => 'SSM',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 16,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría del Bienestar',
                'siglas' => 'SEBI',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 17,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría del Migrante',
                'siglas' => 'SEMIGRANTE',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 18,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría de Igualdad Sustantiva y Desarrollo de las Mujeres Michoacanas',
                'siglas' => 'SEIMUJER',
                'categoria' => 'Secretaría',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 19,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría Ejecutiva del Sistema Estatal de Protección Integral de Niñas, Niños y Adolescentes',
                'siglas' => 'SIPINNA',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 20,
                'id_area_padre' => NULL,
                'nombre' => 'Coordinación del Sistema Penitenciario del Estado de Michoacán',
                'siglas' => 'CSPEMO',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 21,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión de Búsqueda de Personas del Estado de Michoacán',
                'siglas' => 'CBPM',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 22,
                'id_area_padre' => NULL,
                'nombre' => 'Centro Estatal para el Desarrollo Municipal',
                'siglas' => 'CEDEMUN',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 23,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Registral y Catastral del Estado de Michoacán',
                'siglas' => 'IRYCEM',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 24,
                'id_area_padre' => NULL,
                'nombre' => 'Unidad de Inteligencia Patrimonial y Económica del Estado de Michoacán',
                'siglas' => 'UIPEE',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 25,
                'id_area_padre' => NULL,
                'nombre' => 'Servicio de Administración Tributaria del Estado de Michoacán',
                'siglas' => 'SATMICH',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 26,
                'id_area_padre' => NULL,
                'nombre' => 'Procuraduría de Protección al Ambiente',
                'siglas' => 'PROAM',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 27,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto del Transporte del Estado de Michoacán',
                'siglas' => 'INSTRAMICH',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 28,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Michoacano de Ciencias de la Educación "José Mª. Morelos"',
                'siglas' => 'IMCED',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 29,
                'id_area_padre' => NULL,
                'nombre' => 'Orquesta Sinfónica de Michoacán',
                'siglas' => 'OSM',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 30,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Estatal para la Protección contra Riesgos Sanitarios',
                'siglas' => 'COEPRIS',
                'categoria' => 'Organismo Desconcentrado',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 31,
                'id_area_padre' => NULL,
                'nombre' => 'Casa de las Artesanías del Estado de Michoacán',
                'siglas' => 'CASART',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-05-08 02:07:12',
            ],
            [
                'id_area' => 32,
                'id_area_padre' => NULL,
                'nombre' => 'Centro Estatal de Certificación, Acreditación y Control de Confianza del Estado de Michoacán',
                'siglas' => 'CECA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 33,
                'id_area_padre' => NULL,
                'nombre' => 'Centro de Convenciones de Morelia (CECONEXPO)',
                'siglas' => 'CECONEXPO',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 34,
                'id_area_padre' => NULL,
                'nombre' => 'Centro Estatal de Fomento Ganadero del Estado de Michoacán',
                'siglas' => 'CEFOGA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 35,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Estatal del Agua y Gestión de Cuencas (CEAC)',
                'siglas' => 'CEAC',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 36,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Estatal de Cultura Física y Deporte (CECUFID)',
                'siglas' => 'CECUFID',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 37,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Estatal de Arbitraje Médico de Michoacán (COESAMM)',
                'siglas' => 'COESAMM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 38,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Ejecutiva Estatal de Atención a Víctimas',
                'siglas' => 'CEEAV',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 39,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Forestal del Estado (COFOM)',
                'siglas' => 'COFOM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 40,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión de Pesca del Estado de Michoacán (COMPESCA)',
                'siglas' => 'COMPESCA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 41,
                'id_area_padre' => NULL,
                'nombre' => 'Comité de Adquisiciones del Poder Ejecutivo de Michoacán (CADPE)',
                'siglas' => 'CADPE',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 42,
                'id_area_padre' => NULL,
                'nombre' => 'Dirección de Pensiones Civiles del Estado',
                'siglas' => 'DPCM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 43,
                'id_area_padre' => NULL,
                'nombre' => 'Fomento Turístico de Michoacán (FOTURMICH)',
                'siglas' => 'FOTURMICH',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 44,
                'id_area_padre' => NULL,
                'nombre' => 'Fondo Mixto para el Fomento Industrial de Michoacán',
                'siglas' => 'FOMIM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 45,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de Vivienda del Estado de Michoacán (IVEM)',
                'siglas' => 'IVEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 46,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de la Juventud Michoacana',
                'siglas' => 'IJM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 47,
                'id_area_padre' => NULL,
                'nombre' => 'Junta de Asistencia Privada (JAP)',
                'siglas' => 'JAP',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 48,
                'id_area_padre' => NULL,
                'nombre' => 'Parque Zoológico "Benito Juárez"',
                'siglas' => 'ZOO-MICH',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 49,
                'id_area_padre' => NULL,
                'nombre' => 'Servicios de Salud de Michoacán',
                'siglas' => 'SSM', // Coincide con Secretaría de Salud
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 50,
                'id_area_padre' => NULL,
                'nombre' => 'Sistema Michoacano de Radio y Televisión',
                'siglas' => 'SMRTV',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 51,
                'id_area_padre' => NULL,
                'nombre' => 'Sistema para el Desarrollo Integral de la Familia Michoacana (DIF)',
                'siglas' => 'DIF',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 52,
                'id_area_padre' => NULL,
                'nombre' => 'Sistema Integral de Financiamiento para el Desarrollo de Michoacán (SI Financia)',
                'siglas' => 'SI FINANCIA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 53,
                'id_area_padre' => NULL,
                'nombre' => 'Consejo Estatal para Prevenir y Eliminar la Discriminación y la Violencia',
                'siglas' => 'COEPREDV',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 54,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Estatal de Estudios Superiores en Seguridad y Profesionalización Policial',
                'siglas' => 'IEESSPP',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 55,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de Defensoría Pública del Estado de Michoacán',
                'siglas' => 'IDP',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 56,
                'id_area_padre' => NULL,
                'nombre' => 'Policía Auxiliar del Estado de Michoacán',
                'siglas' => 'PAM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 57,
                'id_area_padre' => NULL,
                'nombre' => 'Coordinación de Planeación para el Desarrollo del Estado de Michoacán',
                'siglas' => 'COPLADEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 58,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de Ciencia, Tecnología e Innovación del Estado de Michoacán',
                'siglas' => 'ICTI',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 59,
                'id_area_padre' => NULL,
                'nombre' => 'Comisión Estatal para el Desarrollo de los Pueblos Indígenas',
                'siglas' => 'CEDPI',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 60,
                'id_area_padre' => NULL,
                'nombre' => 'Secretaría Ejecutiva del Sistema Estatal Anticorrupción',
                'siglas' => 'SESEA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 61,
                'id_area_padre' => NULL,
                'nombre' => 'Centro de Conciliación Laboral del Estado de Michoacán',
                'siglas' => 'CCLM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 62,
                'id_area_padre' => NULL,
                'nombre' => 'Consejo Económico y Social del Estado de Michoacán',
                'siglas' => 'CESEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 63,
                'id_area_padre' => NULL,
                'nombre' => 'Casa Estatal del Adulto Mayor',
                'siglas' => 'CAAM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 64,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Oncológico del Estado de Michoacán',
                'siglas' => 'IOEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 65,
                'id_area_padre' => NULL,
                'nombre' => 'Colegio de Bachilleres del Estado de Michoacán (COBAEM)',
                'siglas' => 'COBAEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 66,
                'id_area_padre' => NULL,
                'nombre' => 'Colegio de Educación Profesional Técnica del Estado de Michoacán (CONALEPMICH)',
                'siglas' => 'CONALEPMICH',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 67,
                'id_area_padre' => NULL,
                'nombre' => 'Colegio de Estudios Científicos y Tecnológicos del Estado de Michoacán (CECyTEM)',
                'siglas' => 'CECyTEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 68,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de Capacitación para el Trabajo del Estado de Michoacán (ICATMI)',
                'siglas' => 'ICATMI',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 69,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Apatzingán',
                'siglas' => 'ITSA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 70,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Ciudad Hidalgo',
                'siglas' => 'ITSCH',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 71,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Huetamo',
                'siglas' => 'ITSH',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 72,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Los Reyes, Michoacán',
                'siglas' => 'ITSLR',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 73,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Pátzcuaro, Michoacán',
                'siglas' => 'ITSP',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 74,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior Purépecha',
                'siglas' => 'ITSPur',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 75,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Tacámbaro, Michoacán',
                'siglas' => 'ITST',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 76,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Uruapan',
                'siglas' => 'ITSU',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 77,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico de Estudios Superiores de Zamora',
                'siglas' => 'ITESZA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 78,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico de Estudios Superiores de Puruándiro',
                'siglas' => 'ITESPU',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 79,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad de la Ciénega del Estado de Michoacán de Ocampo',
                'siglas' => 'UCEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 80,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Intercultural Indígena de Michoacán',
                'siglas' => 'UIIM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 81,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Tecnológica de Morelia (UTM)',
                'siglas' => 'UTM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 82,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Virtual del Estado de Michoacán',
                'siglas' => 'UNIVIM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 83,
                'id_area_padre' => NULL,
                'nombre' => 'Telebachillerato Michoacán',
                'siglas' => 'TEBAEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 84,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto Tecnológico Superior de Coalcomán, Michoacán',
                'siglas' => 'ITSC',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 85,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Politécnica de Uruapan',
                'siglas' => 'UPU',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 86,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Politécnica de Lázaro Cárdenas, Michoacán',
                'siglas' => 'UPLC',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 87,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Tecnológica del Oriente de Michoacán',
                'siglas' => 'UTOM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 88,
                'id_area_padre' => NULL,
                'nombre' => 'Instituto de Educación Media Superior y Superior del Estado de Michoacán',
                'siglas' => 'IEMSSySEM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 89,
                'id_area_padre' => NULL,
                'nombre' => 'Universidad Intercultural Tecnológica y Politécnica de Aquila, Michoacán',
                'siglas' => 'UITPA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 90,
                'id_area_padre' => NULL,
                'nombre' => 'Compañía Inmobiliaria Fomento Turístico de Michoacán S.A. de C.V.',
                'siglas' => 'CIFTUM',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 91,
                'id_area_padre' => NULL,
                'nombre' => 'Junta Local de Conciliación y Arbitraje',
                'siglas' => 'JLCA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
            [
                'id_area' => 92,
                'id_area_padre' => NULL,
                'nombre' => 'Tribunal de Conciliación y Arbitraje',
                'siglas' => 'TCA',
                'categoria' => 'Entidad',
                'is_active' => 1,
                'created_at' => '2025-04-11 19:15:56',
                'updated_at' => '2025-04-11 19:15:56',
            ],
        
        ];

        // Insertar los datos
        DB::table('cat_areas_gob')->insert($areas);

        // Volver a activar la verificación de claves foráneas
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
